### ISSUE TITLE
facing error: "github.com/iansmith/d3/d3.go:52:16: cannot use self.obj.Call("selectAll", string(n)) (type *js.Object) as type js.Object in field value"

### ISSUE THREAD

**Issue by mindmithun** [iansmith/d3#8]
Thank you for the d3 package:

I am trying to get this package installed in my Linux Mint 17.3 box and getting the following errors:

$ go get -u github.com/gopherjs/gopherjs
$ go get github.com/gopherjs/jquery
$ go get -u honnef.co/go/js/dom

$ go get -u github.com/iansmith/d3
# github.com/iansmith/d3
project/src/github.com/iansmith/d3/d3.go:52:16: cannot use self.obj.Call("selectAll", string(n)) (type *js.Object) as type js.Object in field value
project/src/github.com/iansmith/d3/d3.go:60:16: cannot use self.obj.Call("data", arr) (type *js.Object) as type js.Object in field value
project/src/github.com/iansmith/d3/d3.go:67:16: cannot use self.obj.Call("enter") (type *js.Object) as type js.Object in field value
project/src/github.com/iansmith/d3/d3.go:75:16: cannot use self.obj.Call("append", string(n)) (type *js.Object) as type js.Object in field value
project/src/github.com/iansmith/d3/d3.go:84:16: cannot use self.obj.Call("style", string(prop), f) (type *js.Object) as type js.Object in field value
project/src/github.com/iansmith/d3/d3.go:92:16: cannot use self.obj.Call("style", string(prop), value) (type *js.Object) as type js.Object in field value
project/src/github.com/iansmith/d3/d3.go:101:16: cannot use self.obj.Call("text", f) (type *js.Object) as type js.Object in field value
project/src/github.com/iansmith/d3/d3.go:109:16: cannot use self.obj.Call("text", v) (type *js.Object) as type js.Object in field value
project/src/github.com/iansmith/d3/d3.go:116:16: cannot use self.obj.Call("attr", string(p), v) (type *js.Object) as type js.Object in field value
project/src/github.com/iansmith/d3/d3.go:123:16: cannot use self.obj.Call("attr", string(p), v) (type *js.Object) as type js.Object in field value
project/src/github.com/iansmith/d3/d3.go:123:16: too many errors

//----------------------------------------------------------------------------------------------------------------------------------------//

My system info:

$ cat /etc/*release*
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.2
DISTRIB_CODENAME=rafaela
DISTRIB_DESCRIPTION="Linux Mint 17.2 Rafaela"
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.2
DISTRIB_CODENAME=rafaela
DISTRIB_DESCRIPTION="Linux Mint 17.2 Rafaela"
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
cat: /etc/upstream-release: Is a directory

**Comment by cryptix** [comment]
Are you trying to compile this for the new wasm GOARCH target? I think this was made for gopherjs which has a slightly different js API

**Comment by mindmithun** [comment]
I have never used gopherjs before. I am using the same GOPATH and GOBIN settings which I use for native Go. I mean go run, go install, go build works fine.

**Comment by cryptix** [comment]
>  I am using the same GOPATH and GOBIN settings which I use for native Go

that should be fine. when you use `gopherjs build` to compile your project, this error shouldn't show up then.

Other than that you need input from @iansmith on this. I haven't touched gopherjs since the release of go1.11 - I _think_ there might have been a breaking change which makes it compatible to the wasm syscall/js package. (Compare [stdlib syscall/js](https://godoc.org/syscall/js) with [gopherjs/js](https://godoc.org/github.com/gopherjs/gopherjs/js))

The main difference is that `Call` returns a _pointer_ to a js.Object in one and not the other. If you want to use this d3 package in wasm, you might get away with changing [d3.go:43ff](https://github.com/iansmith/d3/blob/c572d88f3ef66f34cad4ef194559936f8fe684eb/d3.go#L43) to


```go
//selectionImpl is the implementation of Selection.
type selectionImpl struct {
	obj *js.Object
}
```

**Comment by mindmithun** [comment]
I am not using Go anymore for my project. Thank you for the support. Appreciated.
